# Generated by Django 2.2.3 on 2019-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_text', models.CharField(max_length=200)),
                ('spend_value', models.FloatField()),
                ('spend_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
