# Generated by Django 2.2.3 on 2019-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspends_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='spend_date',
            field=models.DateField(),
        ),
    ]
