# Generated by Django 2.2.3 on 2019-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspends_app', '0002_auto_20190721_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='spend_owner',
            field=models.IntegerField(default=0),
        ),
    ]
