# Generated by Django 2.2.3 on 2019-08-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspends_app', '0003_spend_spend_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_label_owner', models.IntegerField(default=0)),
                ('payment_label_text', models.CharField(max_length=50)),
                ('payment_label_color', models.CharField(max_length=50)),
            ],
        ),
    ]
