# Generated by Django 2.2.3 on 2019-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspends_app', '0004_paymentlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlabel',
            name='payment_label_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
