# Generated by Django 2.2.3 on 2019-08-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myspends_app', '0005_auto_20190803_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='spend_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myspends_app.PaymentLabel'),
        ),
    ]
